name: Deploy Vite para GitHub Pages

on:
  push:
    branches: ["main"] # Altere para "master" se a sua branch principal tiver esse nome
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Configurar Pages
        uses: actions/configure-pages@v5

      - name: Instalar dependências e buildar
        run: |
          npm ci
          npm run build

      - name: Upload do artefato
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # O Vite joga os arquivos convertidos aqui

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy para o GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
